version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: bracket-hub
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_USER =$DB_USER
      - DB_PASSWORD =$DB_PASSWORD
      - JWTSECRET =$JWTSECRET
      - PORT =$PORT
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    command: ./bin/wait-for.sh db:9042 -- /home/node/app/node_modules/.bin/nodemon index.js 

  db:
    image: cassandra
    container_name: db
    restart: unless-stopped
    ports:
      - 9042:9042
    # volumes:     
    #   - dbdata:/data/db
    volumes:
      - dbdata:/bin/db/ks1.cql
    command: /bin/sh -c "echo loading cassandra keyspace && cqlsh cassandra -f /ks1.cql"
    networks:
      - app-network  
    # entrypoint: ["./bin/init.sh"]

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: